name: xas_env
channels:
  - plotly
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - matplotlib[version='>3.0*']
  - pandas
  - scipy[version='>1.6*']
  - scikit-learn
  - numpy[version='>1.20*']
  - tomopy
  - wxpython
  - pycifrw
  - pymatgen
  - seaborn
  - asttokens
  - tornado
  - python-dateutil
  - debugpy
  - ipython
  - openssl
  - backcall
  - setuptools
  - libzlib
  - pickleshare
  - colorama
  - traitlets
  - bzip2
  - libffi
  - matplotlib-inline
  - nest-asyncio
  - sqlite
  - xz
  - tzdata
  - certifi
  - pure_eval
  - pygments
  - wheel
  - pyzmq
  - pip
  - jedi
  - zlib
  - prompt-toolkit
  - entrypoints
  - pywin32
  - ca-certificates
  - jupyter_client
  - jupyter_core
  - jupyter
  - wcwidth
  - executing
  - decorator
  - six
  - parso
  - tk
  - stack_data
  - ipykernel
  - lmfit
  - plotly
  - plotly_express
  - nbformat
  - python-kaleido
  - tqdm
  - pip:
    - xraylarch==0.9.64
    - watchdog==2.1.9
