name: Publish to PyPI and TestPyPI

on:
  release: 
    types: [published]  # Trigger on release publication
  workflow_dispatch:  # Allow manual trigger
    inputs:
      task:
        type: choice
        options: [release, test-release]
        default: release
        description: 'Release to PyPI or TestPyPI.'

permissions:
  contents: read  # Required for reading the repository contents

jobs:
  build_sdist:
    name: Build distributions
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repository
        uses: actions/checkout@v4

      - name: Install Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"  # Specify the Python version you want to use
      
      - name: Build source distribution
        run: |
          pip install build
          python -m build --sdist

      - uses: actions/upload-artifact@v4
        with:
          path: dist/*.tar.gz  # Upload the source distribution

  build_wheels:
    name: Build wheels
    strategy: 
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]  # Specify the OS versions you want to build wheels for
        python-version: ["37", "38", "39", "310", "311", "312"]  # Specify the Python versions you want to build wheels for
    runs-on: ${{ matrix.os }}
    steps: 
      - name: Check out the repository
        uses: actions/checkout@v4

      - name: Build wheels
        uses: pypa/cibuildwheel@v2.23.2
        env:
          CIBW_BUILD: cp${{ matrix.python-version }}-*  # Build for all platforms

      - name: Save artifacts
        uses: actions/upload-artifact@v4
        with:
          name: dist-${{ matrix.os }}-${{ matrix.python-version }}
          path: ./wheelhouse/*.whl  # Upload the built wheels

  release:
    needs: [build_sdist, build_wheels]
    runs-on: ubuntu-latest
    environment:
      name: pypi
      url: https://pypi.org/p/autoXAS 
    permissions:
      id-token: write  # Mandatory for trusted publishing
    steps:
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.10"  # Specify the Python version you want to use

    - name: Get build artifacts
      uses: actions/download-artifact@v4
      with:
        pattern: dist-*
        merge-multiple: true  
        path: dist/  

    - name: Publish to PyPI or TestPyPI
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        skip-existing: true
        verbose: true